"""
Configuration file for Smart Attendance System.
"""
from pathlib import Path

# ===== WEBCAM AND VIDEO SETTINGS =====
WEBCAM_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
FPS = 30
CAMERA_BUFFER_SIZE = 1
CAMERA_USE_MJPG = True

# ===== REAL-TIME PERFORMANCE SETTINGS =====
USE_GPU_IF_AVAILABLE = True
FACE_DETECTION_MODEL = "cnn"  # prefer GPU CNN; detector falls back if CUDA dlib is unavailable
FACE_DETECTION_SCALE = 0.5
FACE_DETECTION_INTERVAL = 2
FACE_DETECTION_UPSAMPLE = 0
POSE_PROCESS_SCALE = 0.75
STATS_REFRESH_SECONDS = 1.0
ENABLE_RUNTIME_DEBUG = False

# ===== BEHAVIOR EXTRACTION SETTINGS =====
SEQUENCE_LENGTH = 30
BEHAVIOR_FEATURE_DIM = 99
SEQUENCE_DURATION_SECONDS = 1.0
BEHAVIOR_SEQUENCE_STRIDE_SECONDS = 0.25
REGISTRATION_SEQUENCE_STRIDE_SECONDS = 0.5

# ===== FACE RECOGNITION SETTINGS =====
FACE_RECOGNITION_TOLERANCE = 0.5

# ===== BEHAVIOR CONFIDENCE SETTINGS =====
BEHAVIOR_CONFIDENCE_THRESHOLD = 0.9
PROXY_ALERT_THRESHOLD = 0.40
MIN_BEHAVIOR_MOTION_SCORE = 0.020
MIN_BEHAVIOR_TEMPORAL_STD = 0.015
MIN_BEHAVIOR_DECISION_SECONDS = 3.0

# ===== LIVENESS DETECTION SETTINGS =====
BLINK_TIME_LIMIT = 5
BEHAVIOR_OBSERVATION_TIME = 25
MAX_ATTEMPTS = 3
EYE_AR_THRESHOLD = 0.30
EYE_AR_CONSEC_FRAMES = 2

# ===== ATTENDANCE SETTINGS =====
ATTENDANCE_COOLDOWN_SECONDS = 300
ALLOW_MULTIPLE_ATTENDANCE_PER_DAY = False

# ===== DIRECTORY PATHS =====
BASE_DIR = Path(__file__).parent
KNOWN_FACES_DIR = BASE_DIR / "data" / "known_faces"
BEHAVIOR_DATA_DIR = BASE_DIR / "data" / "behavior_sequences"
MODELS_DIR = BASE_DIR / "models"
DATA_DIR = BASE_DIR / "data"

# ===== DATABASE SETTINGS =====
DB_PATH = BASE_DIR / "data" / "attendance.db"

# Create directories if they don't exist
KNOWN_FACES_DIR.mkdir(parents=True, exist_ok=True)
BEHAVIOR_DATA_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR.mkdir(parents=True, exist_ok=True)

# ===== LOGGING SETTINGS =====
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_LEVEL = "INFO"

# ===== TRACKER SETTINGS =====
MAX_DISAPPEARED_FRAMES = 30
CENTROID_DISTANCE_THRESHOLD = 80
