services:
  - type: web
    name: smart-attendance-api
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: SECRET_KEY
        generateValue: true
